### PR TITLE
Make Security Definition and Security Requirement as Python Objects

### PR DESCRIPTION
**Pull request by macisamuele**
The goal of this PR is to target #123.

As @jlumpe the initial implementation of the security object added by PR #112 was not 100% compliant with the swagger specs. 

To achieve a better matching of the specs I have created specific classes for [Security Definition](http://swagger.io/specification/#securityDefinitionsObject) and [Security Requirement](http://swagger.io/specification/#securityRequirementObject). In this way will be easier to integrate the handling of ``oauth2`` security format.

Main differences:
* ``security_objects`` property of ``operation`` is removed: the definition was incomplete and is replaced by ``security_requirements`` property which returns the list of Security Requirement objects
* the parameters injected due to security specification cannot override parameters required by Path Object or Operation Object (is needed because different constraint could be injected) and are marked as optional parameters (because of the OR between different security requirements, check ``example3`` on issue #123)
* ``unmarshal_request`` performs proper validation of security related parameters:
    * checks that 1 and only one security requirement is matched
    * in case of multiple security requirements are matched, checks that one matching security requirement is a superset of all the others (contains all the others, ie. ``example5`` on issue #123)

I know that reviewing it could be hard ... so I added a _long_ set of tests to guarantee a good coverage of the modifications.

**NOTE**: I'll update ``CHANGELOG.rst`` after the end of the review

### CODE REVIEW

**Comment by jlumpe** [comment]
Can confirm that this is working for me using my simple spec where the API key can be in the query or header.

**Comment by macisamuele** [comment]
I have added test care with apiKey security with parameter in query.

@jlumpe the test modified is checking even that case.

**Comment by macisamuele** [comment]
@sjaensch if you have some time in the next days could you have a look to this? Thanks a lot

**Comment by sjaensch** [comment]
🛳

**Pull request merged**
